// init.ts — `topo init`: install Topo into a repo.
// Idempotent and additive: scaffolds an initial map from a first marker scan,
// installs the agent skill + CLAUDE.md rule note, and a pre-commit drift guard.

import {
  existsSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  copyFileSync,
  chmodSync,
  appendFileSync,
} from 'node:fs'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { defaultConfig, CONFIG_FILE, type ToposConfig } from '../../core/config'
import { mapPath } from '../../core/paths'
import { scanClaims } from '../../core/markers/scan'
import { regenerate } from '../../core/regen/merge'
import { serializeTopos } from '../../core/serialize'

const ASSETS = fileURLToPath(new URL('../../assets/', import.meta.url))

export interface InitOptions {
  dir?: string
  name?: string
  force?: boolean
  hook?: boolean
}

export function runInit(opts: InitOptions): number {
  const root = resolve(opts.dir ?? process.cwd())
  const cfgFile = join(root, CONFIG_FILE)
  if (existsSync(cfgFile) && !opts.force) {
    console.error(`topo: ${CONFIG_FILE} already exists in ${root}. Re-run with --force to reinstall.`)
    return 2
  }

  const base = defaultConfig(root)
  const config: ToposConfig = { ...base, world: opts.name ?? base.world }
  const log = (s: string) => console.log(`  ${s}`)
  console.log(`Installing Topo into ${root}`)

  // 1. config
  writeFileSync(cfgFile, JSON.stringify(config, null, 2) + '\n')
  log(`wrote ${CONFIG_FILE}`)

  // 2. initial map from a first marker scan (crude-but-useful is fine)
  const { claims, filesScanned } = scanClaims(root, config)
  const world = regenerate(claims, null, { worldName: config.world })
  const header = `// ${config.world} — system map. Generated by topo from //@topo markers.`
  writeFileSync(mapPath(root, config), serializeTopos(world, { header }))
  log(`generated ${config.map} (${Object.keys(world.systems).length - 1} systems from ${filesScanned} files)`)

  // 3. agent skill
  const skillDir = join(root, '.claude', 'skills', 'topo-sync')
  mkdirSync(skillDir, { recursive: true })
  copyFileSync(join(ASSETS, 'skill', 'SKILL.md'), join(skillDir, 'SKILL.md'))
  log(`installed .claude/skills/topo-sync/SKILL.md`)

  // 4. CLAUDE.md rule note
  const claudeMd = join(root, 'CLAUDE.md')
  const note = readFileSync(join(ASSETS, 'claude-rule.md'), 'utf8')
  if (!existsSync(claudeMd)) {
    writeFileSync(claudeMd, `# ${config.world}\n\n${note}`)
    log(`created CLAUDE.md with the Topo rule note`)
  } else if (!readFileSync(claudeMd, 'utf8').includes('## Topo system map')) {
    appendFileSync(claudeMd, `\n${note}`)
    log(`appended the Topo rule note to CLAUDE.md`)
  } else {
    log(`CLAUDE.md already has the Topo rule note (skipped)`)
  }

  // 5. pre-commit hook
  if (opts.hook !== false) {
    const hooksDir = join(root, '.git', 'hooks')
    if (existsSync(hooksDir)) {
      const hookFile = join(hooksDir, 'pre-commit')
      if (!existsSync(hookFile)) {
        copyFileSync(join(ASSETS, 'pre-commit'), hookFile)
        chmodSync(hookFile, 0o755)
        log(`installed .git/hooks/pre-commit (drift blocker)`)
      } else if (!readFileSync(hookFile, 'utf8').includes('Topo drift guard')) {
        appendFileSync(
          hookFile,
          `\n# --- Topo drift guard (added by topo init) ---\nif command -v topo >/dev/null 2>&1; then topo check || exit 1; else npx --no-install topo check || exit 1; fi\n`,
        )
        log(`appended a Topo drift check to the existing pre-commit hook`)
      } else {
        log(`pre-commit hook already has the Topo drift guard (skipped)`)
      }
    } else {
      log(`no .git/hooks found — skipped the pre-commit hook`)
    }
  }

  console.log('\nDone. Next:')
  console.log('  • topo check   — verify the map matches the markers')
  console.log('  • topo view    — watch the live map in your browser')
  console.log("  • add //@topo markers as you code; 'topo propose' updates the map")
  return 0
}
