// regen.ts — `topo regen` / `topo propose`: rebuild the map from markers.
// Default writes the DRAFT (system.draft.topo) for human approval; --write is the
// discouraged escape hatch that edits the live map directly.

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { loadConfig } from '../../core/config'
import { mapPath, draftPath, draftMetaPath } from '../../core/paths'
import { scanClaims } from '../../core/markers/scan'
import { parseTopos, type ToposWorld } from '../../core/topos'
import { serializeTopos } from '../../core/serialize'
import { regenerate } from '../../core/regen/merge'
import { summarizeDiff, extractHeader, isEmptyDiff, type DraftMeta } from '../../core/regen/draft'
import { sha256 } from '../../core/hash'

export interface RegenOptions {
  dir?: string
  write?: boolean
  json?: boolean
}

export function runRegen(opts: RegenOptions): number {
  const { root, config } = loadConfig(opts.dir ?? process.cwd())
  const { claims } = scanClaims(root, config)

  const mp = mapPath(root, config)
  let prior: ToposWorld | null = null
  let priorText = ''
  if (existsSync(mp)) {
    priorText = readFileSync(mp, 'utf8')
    const { world, error } = parseTopos(priorText)
    if (error || !world) {
      console.error(`topo: failed to parse ${config.map}: ${error ?? 'no world found'}`)
      return 2
    }
    prior = world
  }

  const world = regenerate(claims, prior, { worldName: config.world })
  const header = extractHeader(priorText) ?? `// ${world.root} — system map. Generated by topo from //@topo markers.`
  const text = serializeTopos(world, { header })
  const summary = summarizeDiff(prior, world)

  if (opts.write) {
    writeFileSync(mp, text)
    if (opts.json) console.log(JSON.stringify({ wrote: config.map, summary }, null, 2))
    else console.log(`Wrote ${config.map}  (+${summary.added.length} ~${summary.changed.length} -${summary.removed.length})`)
    return 0
  }

  const dp = draftPath(root, config)
  writeFileSync(dp, text)
  const meta: DraftMeta = { base: sha256(priorText), generatedAt: new Date().toISOString(), summary }
  writeFileSync(draftMetaPath(root, config), JSON.stringify(meta, null, 2) + '\n')

  if (opts.json) {
    console.log(JSON.stringify({ draft: config.draft, summary }, null, 2))
  } else {
    console.log(`Proposed ${config.draft}`)
    if (summary.added.length) console.log(`  + added:   ${summary.added.join(', ')}`)
    if (summary.changed.length) console.log(`  ~ changed: ${summary.changed.join(', ')}`)
    if (summary.removed.length) console.log(`  - removed: ${summary.removed.join(', ')}`)
    if (isEmptyDiff(summary)) console.log('  (no structural change)')
    console.log(`Review it in 'topo view', then 'topo approve'.`)
  }
  return 0
}
