// sync.ts — `topo sync`: regenerate the LIVE map from markers.
//
// This is the agent's normal loop: edit code → update //@topo markers →
// `topo sync` → `topo check` (green). `propose`/`approve` are the optional
// human-review gate, not this. Markers are the source of truth; sync makes the
// live map match them while preserving the map's design judgment (thing schemas,
// gateways, descriptions, explicit connection overrides — see regenerate()).

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { loadConfig } from '../../core/config'
import { mapPath } from '../../core/paths'
import { scanClaims } from '../../core/markers/scan'
import { parseTopos, type ToposWorld } from '../../core/topos'
import { serializeTopos } from '../../core/serialize'
import { regenerate } from '../../core/regen/merge'
import { summarizeDiff, extractHeader, isEmptyDiff } from '../../core/regen/draft'

export interface SyncOptions {
  dir?: string
  json?: boolean
}

export function runSync(opts: SyncOptions): number {
  const { root, config } = loadConfig(opts.dir ?? process.cwd())
  const { claims } = scanClaims(root, config)

  const mp = mapPath(root, config)
  let prior: ToposWorld | null = null
  let priorText = ''
  if (existsSync(mp)) {
    priorText = readFileSync(mp, 'utf8')
    const { world, error } = parseTopos(priorText)
    if (error || !world) {
      console.error(`topo: failed to parse ${config.map}: ${error ?? 'no world found'}`)
      return 2
    }
    prior = world
  }

  const world = regenerate(claims, prior, { worldName: config.world })
  const header = extractHeader(priorText) ?? `// ${world.root} — system map. Generated by topo from //@topo markers.`
  const text = serializeTopos(world, { header })
  const summary = summarizeDiff(prior, world)

  writeFileSync(mp, text)

  if (opts.json) {
    console.log(JSON.stringify({ synced: config.map, summary }, null, 2))
    return 0
  }
  if (isEmptyDiff(summary)) {
    console.log(`${config.map} already matches the markers.`)
  } else {
    console.log(`Synced ${config.map}  (+${summary.added.length} ~${summary.changed.length} -${summary.removed.length}) — it now matches the markers.`)
  }
  console.log(`Next: 'topo check' to confirm it's green, 'topo view' to watch it live.`)
  return 0
}
